INSERT INTO `supers` (`super_id`, `name`) VALUES
(1, 'Advance Retirement Savings Account'),
(2, 'Advance Retirement Suite'),
(3, 'Aero Superannuation Fund'),
(4, 'Agco Australia Superannuation Plan'),
(5, 'AIA Superannuation Fund'),
(6, 'Alcoa of Australia Retirement Plan'),
(7, 'AMG Universal Super'),
(8, 'AMP Eligible Rollover Fund'),
(9, 'AMP Retirement Trust'),
(10, 'AMP Superannuation Savings Trust'),
(11, 'ANZ Australian Staff Superannuation Scheme'),
(12, 'Aon Eligible Rollover Fund'),
(13, 'AON Master Trust'),
(14, 'Ardagh Australia Superannuation Fund'),
(15, 'ASGARD Independence Plan Division Four'),
(16, 'ASGARD Independence Plan Division Two'),
(17, 'AusBev Superannuation Fund'),
(18, 'Auscoal Superannuation Fund'),
(19, 'Australia Post Superannuation Scheme'),
(20, 'Australia''s Unclaimed Super Fund'),
(21, 'Australian Catholic Superannuation and Retirement Fund'),
(22, 'Australian Christian Superannuation Fund '),
(23, 'Australian Eligible Rollover Fund'),
(24, 'Australian Ethical Retail Superannuation Fund'),
(25, 'Australian Meat Industry Superannuation Trust'),
(26, 'AustralianSuper'),
(27, 'Austsafe Superannuation Fund'),
(28, 'Avanteos Superannuation Trust'),
(29, 'AvSuper Fund'),
(30, 'AvWrap Retirement Service'),
(31, 'Bankwest Staff Superannuation Plan'),
(32, 'Beacon Superannuation Plan'),
(33, 'Benchmark Mutual Superannuation Plan'),
(34, 'Betros Bros Superannuation Fund No 2'),
(35, 'BHP Billiton Superannuation Fund'),
(36, 'Bluescope Steel Superannuation Fund'),
(37, 'Boc Gases Superannuation Fund'),
(38, 'BT Classic Lifetime'),
(39, 'BT Lifetime Super'),
(40, 'BT Lifetime Super – Employer Plan'),
(41, 'BT Superannuation Savings Fund'),
(42, 'Building Unions Superannuation Scheme (Queensland)'),
(43, 'Bundaberg Sugar Ltd Superannuation Plan'),
(44, 'CareSuper'),
(45, 'Catholic Superannuation Fund'),
(46, 'CBH Superannuation Fund'),
(47, 'Challenger Retirement Fund'),
(48, 'Chifley Super'),
(49, 'Christian Super'),
(50, 'Citibank Australia Staff Superannuation Fund'),
(51, 'Clark Group Superannuation Fund'),
(52, 'ClearView Retirement Plan'),
(53, 'Clough Superannuation Fund'),
(54, 'Club Plus Superannuation Scheme'),
(55, 'Club Super'),
(56, 'Coal Industry Superannuation Fund'),
(57, 'Colonial First State FirstChoice Superannuation Trust'),
(58, 'Colonial First State Rollover & Superannuation Fund'),
(59, 'Colonial Super Retirement Fund'),
(60, 'Combined Fund'),
(61, 'CommInsure Corporate Insurance Superannuation Trust'),
(62, 'Commonwealth Bank Approved Deposit Fund'),
(63, 'Commonwealth Bank Group Super'),
(64, 'Commonwealth Essential Super'),
(65, 'Concept One Superannuation Plan'),
(66, 'Construction & Building Unions Superannuation'),
(67, 'Crown Employees (NSW Fire Brigades Firefighting Staff Death & Disability) Superannuation Fund'),
(68, 'Commonwealth Superannuation Scheme Fund'),
(69, 'CUBS Superannuation Fund'),
(70, 'DBP Master Superannuation Plan'),
(71, 'Definitive Superannuation Plan'),
(72, 'Deseret Benefit Plan for Australia'),
(73, 'DIY Master Plan'),
(74, 'Dow Australia Superannuation Fund'),
(75, 'DPM Retirement Service'),
(76, 'Duluxgroup Employees Superannuation Fund'),
(77, 'e-Clipse Super'),
(78, 'Elphinstone Group Superannuation Fund'),
(79, 'EmPlus Superannuation Fund'),
(80, 'Encircle Superannuation Fund (run by Colonial First State)'),
(81, 'Energy Industries Superannuation Scheme-Pool A'),
(82, 'Energy Industries Superannuation Scheme-Pool B'),
(83, 'Energy Super'),
(84, 'Enterprise Super'),
(85, 'equipsuper'),
(86, 'EquitySuper'),
(87, 'ExxonMobil Superannuation Plan'),
(88, 'Fairbrother Employees Retirement Fund'),
(89, 'Fiducian Superannuation Fund'),
(90, 'Fire and Emergency Services Superannuation Fund (FES Super)'),
(91, 'First Quest Retirement Service'),
(92, 'First State Superannuation Scheme (First State Super)'),
(93, 'First Super'),
(94, 'FM Insurance Company Ltd Superannuation Fund'),
(95, 'FreshFood Superannuation Fund'),
(96, 'Gillette Australia Superannuation Fund'),
(97, 'Goldman Sachs & JBWere Superannuation Fund'),
(98, 'Grosvenor Pirie Master Superannuation Fund Series 2'),
(99, 'Grow Super'),
(100, 'Guild Retirement Fund (Guild Super and Guild Pension)'),
(101, 'Hannover Life Re of Australasia Ltd Superannuation Plan'),
(102, 'Harwood Superannuation Fund'),
(103, 'Health Employees Superannuation Trust Australia (HESTA)'),
(104, 'Health Industry Plan (HIP Super)'),
(105, 'Heidelberg Australia Superannuation Fund'),
(106, 'HHH Superannuation Fund'),
(107, 'HLB Mann Judd Superannuation Fund'),
(108, 'Holden Employees Superannuation Fund'),
(109, 'HOSTPLUS Superannuation Fund'),
(110, 'HUB24 Super Fund'),
(111, 'IAG & NRMA Superannuation Plan'),
(112, 'Incitec Pivot Employees Superannuation Fund'),
(113, 'ING Direct Superannuation Fund'),
(114, 'Integral Superannuation Fund'),
(115, 'Intrust Super Fund'),
(116, 'IOOF Portfolio Service Superannuation Fund'),
(117, 'IRIS Superannuation Fund'),
(118, 'ISARF Superannuation Fund'),
(119, 'ITG Australia Ltd Superannuation Fund'),
(120, 'Itochu Australia Superannuation Plan'),
(121, 'Kellogg Retirement Fund'),
(122, 'Kinetic Superannuation Fund'),
(123, 'Kingston Superannuation Trust'),
(124, 'L&H Group Superannuation Fund'),
(125, 'Labour Union Co-Operative Retirement Fund (LUCRF)'),
(126, 'Law Employees Superannuation Fund (LESF)'),
(127, 'legalsuper'),
(128, 'Lifefocus Superannuation Fund'),
(129, 'Lifetime Superannuation Fund'),
(130, 'Linfox Staff Superannuation Fund'),
(131, 'Local Authorities Superannuation Fund (Vision Super)'),
(132, 'Local Government Superannuation Scheme (LGS Super)'),
(133, 'Local Government Superannuation Scheme – Pool A'),
(134, 'Local Government Superannuation Scheme – Pool B'),
(135, 'Lutheran Super'),
(136, 'MacMahon Employees Superannuation Fund'),
(137, 'Macquarie ADF Superannuation Fund'),
(138, 'Macquarie Superannuation Plan'),
(139, 'Macquarie University Professorial Superannuation Scheme'),
(140, 'Managed Australian Retirement Fund (MARF)'),
(141, 'Manildra Flour Mills Retirement Fund'),
(142, 'MAP Superannuation Plan'),
(143, 'Maritime Super'),
(144, 'Mars Australia Retirement Plan'),
(145, 'Max Super Fund'),
(146, 'Meat Industry Employees Superannuation Fund'),
(147, 'Media Super'),
(148, 'Mercer Portfolio Service Superannuation Plan'),
(149, 'Mercer Super Trust'),
(150, 'Mercy Super'),
(151, 'Military Superannuation & Benefits Fund No 1'),
(152, 'Millennium Master Trust'),
(153, 'Mines Rescue Stations Staff Superannuation Plan'),
(154, 'MLC Superannuation Fund'),
(155, 'MTAA Superannuation Fund'),
(156, 'Munich Holdings of Australasia Pty Ltd Superannuation Scheme'),
(157, 'National Australia Bank Group Superannuation Fund A'),
(158, 'National Mutual Pro-Super Fund (run by AXA)'),
(159, 'National Mutual Retirement Fund (run by AXA)'),
(160, 'Nationwide Superannuation Fund (NSF)'),
(161, 'NESS Super'),
(162, 'Nestle Australia Group Superannuation Fund'),
(163, 'Netwealth Superannuation Master Fund'),
(164, 'Newcastle Permanent Superannuation Plan'),
(165, 'NGS Super'),
(166, 'Nissan Superannuation Plan'),
(167, 'O-I Australia Superannuation Fund'),
(168, 'Oasis Superannuation Master Trust'),
(169, 'OnePath Masterfund (run by ANZ)'),
(170, 'Onestep Superannuation Fund'),
(171, 'Oracle Superannuation Plan'),
(172, 'Perpetual Super Wrap'),
(173, 'Perpetual WealthFocus Superannuation Fund'),
(174, 'Perpetual’s Select Superannuation Fund'),
(175, 'Personal Choice Private Fund'),
(176, 'Pitcher Retirement Plan'),
(177, 'Plan B Eligible Rollover Fund'),
(178, 'Plan B Superannuation Fund'),
(179, 'Plum Superannuation Fund'),
(180, 'Port of Melbourne Superannuation Fund'),
(181, 'Powerwrap Master Plan'),
(182, 'Premiumchoice Retirement Service'),
(183, 'Prime Superannuation Fund'),
(184, 'Progress Super Fund'),
(185, 'Progressive Superannuation Fund'),
(186, 'Public Eligible Rollover Fund (run by Equity Trustees)'),
(187, 'Public Sector Superannuation Accumulation Plan (PSSap)'),
(188, 'Public Sector Superannuation Scheme (PSS Scheme)'),
(189, 'Qantas Superannuation Plan'),
(190, 'Quadrant Superannuation Scheme'),
(191, 'Queensland Independent Education & Care Superannuation Trust (QIEC Super)'),
(192, 'Rei Super'),
(193, 'Reserve Bank of Australia Officers Superannuation Fund'),
(194, 'Retail Employees Superannuation Trust (REST)'),
(195, 'Retirement Portfolio Service (run by ANZ)'),
(196, 'Retirement Wrap (run by BT)'),
(197, 'Rexel Australia Superannuation Plan'),
(198, 'Rio Tinto Staff Superannuation Fund'),
(199, 'Russell Supersolution Master Trust'),
(200, 'Salic Superannuation Fund'),
(201, 'Scientific Testing & Applied Technical Services Superannuation Plan'),
(202, 'Shell Australia Superannuation Fund'),
(203, 'Smartsave ‘Member’s Choice’ Superannuation Master Plan'),
(204, 'SMF Eligible Rollover Fund'),
(205, 'Staedtler Executive Superannuation Fund'),
(206, 'Star Portfolio Superannuation Fund (run by Colonial First State)'),
(207, 'State Public Sector Superannuation Scheme (Qsuper)'),
(208, 'State Super Fixed Term Pension Plan'),
(209, 'State Super Retirement Fund'),
(210, 'Statewide Superannuation Trust (Statewide Super)'),
(211, 'Stone Superannuation Fund'),
(212, 'Suncorp Defined Benefit Fund'),
(213, 'Suncorp Master Trust'),
(214, 'Sunsuper Superannuation Fund'),
(215, 'Super Directions Fund (run by AXA)'),
(216, 'Super Eligible Rollover Fund'),
(217, 'Super Safeguard Fund'),
(218, 'Super Synergy Fund'),
(219, 'SuperSMA Superannuation Fund'),
(220, 'SuperTrace Eligible Rollover Fund (run by Colonial First State)'),
(221, 'Symetry Personal Retirement Fund (run by Colonial First State)'),
(222, 'Synergy Superannuation Master Fund (run by AXA)'),
(223, 'TAL Superannuation and Insurance Fund'),
(224, 'Tasplan Superannuation Fund'),
(225, 'Taxi Industry Superannuation Fund (Taxi Super)'),
(226, 'Telstra Superannuation Scheme'),
(227, 'The Allied Unions Superannuation Trust (Queensland) (AUSTQ)'),
(228, 'The ARA Retirement Fund'),
(229, 'The Bendigo Superannuation Plan (run by Bendigo Bank)'),
(230, 'The Bird Cameron Superannuation Fund'),
(231, 'The Employees Productivity Award Superannuation Trust'),
(232, 'The Executive Superannuation Fund'),
(233, 'The Flexible Benefits Super Fund'),
(234, 'The ISPF Eligible Rollover Fund'),
(235, 'The James Superannuation Fund'),
(236, 'The Paragon Superannuation Fund'),
(237, 'The Portfolio Service Retirement Fund (run by IOOF)'),
(238, 'The PPS Corporate Superannuation Fund'),
(239, 'The Pressure Dynamics Superannuation Fund'),
(240, 'The Retirement Plan (run by AXA)'),
(241, 'The State Bank Supersafe Approved Deposit Fund'),
(242, 'The Super Money Eligible Rollover Fund (SMERF)'),
(243, 'The Towers Watson Superannuation Fund'),
(244, 'The Transport Industry Superannuation Fund (the TIS fund)'),
(245, 'The Universal Super Scheme (run by MLC)'),
(246, 'The University of Adelaide Superannuation Scheme A 1985'),
(247, 'The University of New England Professorial Superannuation Fund'),
(248, 'The University of New South Wales Professorial Superannuation Fund'),
(249, 'The University of Sydney Professorial Superannuation System'),
(250, 'The University of Wollongong Professorial Superannuation Scheme'),
(251, 'The Victorian Independent Schools Superannuation Fund (VISSF)'),
(252, 'Tidswell Master Superannuation Plan'),
(253, 'Toyota Australia Superannuation Plan'),
(254, 'Toyota Employees Superannuation Trust (Toyota Super)'),
(255, 'TWU Superannuation Fund'),
(256, 'Ultimate Superannuation Fund'),
(257, 'UniSuper'),
(258, 'United Technologies Corporation Retirement Plan'),
(259, 'Uniting Church in Australia Beneficiary Fund'),
(260, 'Victorian Superannuation Fund (VicSuper)'),
(261, 'Virgin Superannuation'),
(262, 'Vision Superannuation Fund (Vision Super)'),
(263, 'WA Local Government Superannuation Plan (WA Local Super)'),
(264, 'Water Corporation Superannuation Plan'),
(265, 'Wealth Personal Superannuation and Pension Fund (run by AXA)'),
(266, 'Westpac Mastertrust – Superannuation Division'),
(267, 'Westpac Personal Superannuation Fund'),
(268, 'Worsley Alumina Superannuation Fund'),
(269, 'Zurich Group Superannuation Fund'),
(270, 'Zurich Master Superannuation Fund');
